[build-system]
requires = ["setuptools>=80"]
build-backend = "setuptools.build_meta"

[project]
name = "mythag-library"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pillow>=12.3.0",
    "pyyaml>=6.0.3",
]

[project.scripts]
mythag-build = "mythag_site.build:main"
mythag-check = "mythag_site.awakeners:check_main"
mythag-serve = "mythag_site.awakeners:serve_main"

[dependency-groups]
dev = [
    "zensical==0.0.53",
]

[tool.setuptools]
packages = ["mythag_site"]
